### ISSUE TITLE
Kotlin dependency in ...-server.jar

### ISSUE THREAD

**Issue by randombyte-developer** [FoxDenStudio/FoxCore#10]
Context: When compiling against foxguard(`compile files("mods/foxcore.jar"`) the plugin gets added to the classpath of my test server(using SpongeStart), the plugin is loaded and works fine. I develop in Kotlin.

A problem arises: First Kotlin warns me that it has found two version of the Kotlin runtime and secondly a newly added method from the Kotlin stdlib doesn't work(`Map<K, V>.getValue(key: K): V`, was added in Kotlin 1.1.).
All this is because the Kotlin runtime in FoxCore isn't relocated, it should be somewhere like `net.foxdenstudio.sponge.foxcore.shaded.kotlin`. See how I do it: [build.gradle](https://github.com/randombyte-developer/claim-blocks/blob/master/build.gradle#L42)
I don't see where you explicitly add the runtime to the final jar but it is happening.

**Comment by vectrixdevelops** [comment]
This should soon be fixed when @gravityfox replaces MapDB with another system I think (as MapDB contains the dependency).

**Comment by gravityfox** [comment]
So a few comments here:
I really should update that kotlin dependency or get rid of it.
I don't really want to relocate it, because if i want to use kotlin in foxguard, i'd have to use extra configuration to relocate the classes for foxguard as well.
I DO have a maven repo, as well as some docs for it, which would fix a lot of dependency debacles.

Ultimately i think i'm going to get rid of my mapDB dependency, but that's still gonna be a while. I have been unable to work on this project due to university being a pain.

**Comment by gravityfox** [comment]
@randombyte-developer honestly, your best bet for now is to just go into the foxcore jar and delete kotlin from it. It should use the newer version you have and be fine.

**Comment by randombyte-developer** [comment]
Ok, leaving this open until it is really resolved.

**Comment by randombyte-developer** [comment]
I guess this is fixed.
